from pathlib import Path
import argparse


def integrate_motifs(input_dirs, out_file):
    of = open(out_file, 'w')
    homer_names = set()
    for input_dir in input_dirs:
        motif_dir_path = Path(input_dir) / 'knownResults'
        for motifFile in motif_dir_path.glob('*.motif'):
            with open(motifFile) as f:
                for line in f:
                    if line.startswith('>'):
                        h_name = line.split('\t')[1]
                        if h_name in homer_names:
                            break
                        else:
                            homer_names.add(h_name)
                    # of.write(line)
    print(len(homer_names))
    i = 0
    for input_dir in input_dirs:
        motif_dir_path = Path(input_dir) / 'knownResults'
        for motifFile in motif_dir_path.glob('*.motif'):
            f = open(motifFile)
            line = f.readline()
            f.close()
            if line.startswith('>'):
                h_name = line.split('\t')[1]
                if h_name in homer_names:
                    i += 1
                    print(i, h_name, motifFile)
                    with open(motifFile) as f:
                        for line in f:
                            # of.write(str(i)+" "+line)
                            of.write(line)
                    homer_names.remove(h_name)
    of.close()


def main():
    parser = argparse.ArgumentParser(description='HOMER software auxiliary tools')
    subparsers = parser.add_subparsers(dest='sub', required=True, title='command',
                                       description='The available commands',
                                       help='select a sub command to use')
    # =====================================================================
    parser_integrate = subparsers.add_parser('integrate',
                                             help='Integrate the results from findMotifsGenome.pl')
    parser_integrate.add_argument('-i', '--input', required=True,
                                  help='the input results directories generated by findMotifsGenome.pl split by ","')
    parser_integrate.add_argument('-o', '--outfile', help='the output file')
    parser_integrate.add_argument('-v', '--version', action='version', version='0.1')

    args = parser.parse_args()
    if args.sub == 'integrate':
        integrate_motifs(args.input.split(','), args.outfile)
    else:
        parser.print_help()
